name: Linux JPackage
# 定义被其他工作流程调用以及手动触发工作流程
on:
  - workflow_call
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    name: build-linux
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 21
          distribution: temurin
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Execute build
        run: ./gradlew --info --stacktrace build
      - name: Execute jlink
        run: ./gradlew --info --stacktrace jlink
      - name: Execute jpackage
        run: ./gradlew --info --stacktrace jpackage
      # 上传产品
      - name: Upload DEB as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: PostJFX-jdk-21-linux-deb
          path: build/jpackage/*.deb
      - name: Upload RPM as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: PostJFX-jdk-21-linux-rpm
          path: build/jpackage/*.rpm
