name: Gradle JPackage Build
# 定义在推送tag时触发工作流程与手动触发工作流程
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build-linux:
    name: Build on linux
    uses: ./.github/workflows/single-build.yml
    with:
      java-version: 21
      platform: ubuntu
  build-windows:
    name: Build on windows
    uses: ./.github/workflows/single-build.yml
    with:
      java-version: 21
      platform: windows
  build-macos:
    name: Build on macos
    uses: ./.github/workflows/single-build.yml
    with:
      java-version: 21
      platform: macos