name: Gradle JPackage Build
# 定义在推送tag时触发工作流程与手动触发工作流程
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  call-linux:
    uses: ./.github/workflows/build-linux.yml
  call-windows:
    uses: ./.github/workflows/build-windows.yml
  call-macos:
    uses: ./.github/workflows/build-macos.yml