name: Windows Native-Image Build
# 定义在推送tag时触发工作流程与手动触发工作流程
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      # 安装GraalVM，配置JAVA_HOME GRAALVM_HOME
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      # 使用 Gradle 构建您的项目
      - name: GraalVM Native Build
        run:
          .\gradlew nativeBuild
      # 上传打包完成后的产品，以供下载
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: PostJFX-graalvm
          path: build/gluonfx/x86_64-windows/*.exe

